# .github/workflows/main.yaml
name: Full MacOS dotfiles setup_quanianitis

on:
  workflow_dispatch:

jobs:
  setup-quanianitis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install stow
        run: brew install stow

      - name: Full install
        continue-on-error: true
        env:
          ENABLE_CICD: "true"
          ACTIONS_WORKSPACE: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          zsh -c "$(curl -fsSL https://raw.githubusercontent.com/quanianitis/dotfiles/refs/heads/main/install)"

      - name: Post-Installation Verification
        run: |
          trimmed_workspace=$(echo "${{ github.workspace }}" | sed 's/\/dotfiles\/dotfiles/\/dotfiles/')
          cat $trimmed_workspace/.config/alacritty/* || true
          cat $trimmed_workspace/.config/helix/* || true
          cat $trimmed_workspace/.zshrc || true
          ls $trimmed_workspace/.config || true
