# .github/workflows/main.yaml
name: MacOS Build setup_quanianitis

on:
  push:
    branches:
      - staging
      - main

jobs:
  setup-quanianitis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install stow
        run: brew install stow

      - name: Build Go
        run: GOOS=darwin go build -o setup_quanianitis

      - name: Test Go
        run: go test -v ./...

      - name: Run setup_quanianitis
        run: ./setup_quanianitis
        continue-on-error: true
        env:
          ENABLE_CICD: "true"
          ACTIONS_WORKSPACE: ${{ github.workspace }}

      - name: Post-Installation Verification
        run: |
          trimmed_workspace=$(echo "${{ github.workspace }}" | sed 's/\/dotfiles\/dotfiles/\/dotfiles/')
          cat $trimmed_workspace/.config/alacritty/* || true
          cat $trimmed_workspace/.config/helix/* || true
          cat $trimmed_workspace/.zshrc || true
          ls $trimmed_workspace/.config || true

